# Generated by Django 5.2.3 on 2025-07-06 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0002_albumlike_songlike"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Annotation",
            fields=[
                ("annotation_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "description",
                    models.TextField(
                        help_text="Ваши пояснения к выделенному фрагменту",
                        verbose_name="Текст аннотации",
                    ),
                ),
                (
                    "photo_url",
                    models.URLField(
                        blank=True,
                        help_text="Опциональная иллюстрация к пояснению",
                        verbose_name="Изображение (URL)",
                    ),
                ),
                (
                    "start_idx",
                    models.PositiveIntegerField(
                        help_text="Позиция первого символа в тексте песни",
                        verbose_name="Начальный индекс",
                    ),
                ),
                (
                    "end_idx",
                    models.PositiveIntegerField(
                        help_text="Позиция последнего символа в тексте песни",
                        verbose_name="Конечный индекс",
                    ),
                ),
                (
                    "fragment",
                    models.TextField(
                        blank=True,
                        help_text="Копия выделенного текста",
                        verbose_name="Фрагмент текста",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False, verbose_name="Одобрено модератором"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор аннотации",
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="music.song",
                        verbose_name="Песня",
                    ),
                ),
            ],
            options={
                "verbose_name": "Аннотация",
                "verbose_name_plural": "Аннотации",
                "ordering": ["-created_at"],
            },
        ),
    ]
