# Generated by Django 5.2.3 on 2025-07-16 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EditSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(verbose_name="ID объекта")),
                (
                    "field_name",
                    models.CharField(
                        help_text="Например: title, description, cover, lyrics и т.п.",
                        max_length=100,
                        verbose_name="Поле для правки",
                    ),
                ),
                (
                    "old_value",
                    models.TextField(
                        blank=True,
                        help_text="Автозаполняется при создании, но можно оставить пустым",
                        verbose_name="Старое значение",
                    ),
                ),
                ("new_value", models.TextField(verbose_name="Предлагаемое значение")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "В ожидании"),
                            ("approved", "Одобрено"),
                            ("rejected", "Отклонено"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Когда предложено"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Когда изменён статус"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Тип объекта",
                    ),
                ),
                (
                    "moderated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="edit_suggestions_moderated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто подтвердил/отклонил",
                    ),
                ),
                (
                    "suggested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edit_suggestions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто предложил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предложение правки",
                "verbose_name_plural": "Предложения правок",
                "ordering": ["-created_at"],
            },
        ),
    ]
