# Generated by Django 5.2.3 on 2025-07-01 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Имя артиста"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, unique=True, verbose_name="URL"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="artist_avatars/",
                        verbose_name="Аватар",
                    ),
                ),
                (
                    "homepage_image",
                    models.ImageField(
                        default="default_homepage.png", upload_to="homepages/"
                    ),
                ),
            ],
            options={
                "verbose_name": "Артист",
                "verbose_name_plural": "Артисты",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ArtistClaimed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "В ожидании"),
                            ("approved", "Подтверждена"),
                            ("rejected", "Отклонена"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата подачи"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата изменения статуса"
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="artists.artist",
                    ),
                ),
                (
                    "moderated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="artist_claims_moderated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artist_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка артиста",
                "verbose_name_plural": "Заявки артистов",
                "ordering": ["-created_at"],
                "unique_together": {("user", "artist")},
            },
        ),
        migrations.CreateModel(
            name="ArtistLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(max_length=100, verbose_name="Платформа"),
                ),
                ("url", models.URLField(verbose_name="Ссылка")),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="artists.artist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ссылка артиста",
                "verbose_name_plural": "Ссылки артиста",
                "unique_together": {("artist", "platform", "url")},
            },
        ),
    ]
